# Generated by Django 4.0.6 on 2022-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_nice_remove_post_likes_post_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timesedited',
            field=models.DateTimeField(null=True),
        ),
    ]
