# Generated by Django 4.0.6 on 2022-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_timesedited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timesedited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
